### ISSUE TITLE
Bug: Light / Vision artifacts in Chrome

### ISSUE THREAD

**Issue by trzpiot** [cyruzzo/AboveVTT#2097]
## Description

With `Line of Sight/Darkness Opacity > 0`, artifacts occur (see screenshot) if there are more than 5 tokens on the map. The problem occurs with both the DM view and the players view. The problem only occurs in Chrome, it works in Firefox.

## Version

1.12

## Screenshot

![Screenshot from 2024-04-28 15-56-51](https://github.com/cyruzzo/AboveVTT/assets/33252305/ceb63feb-3708-47c3-ba41-7049bef48d96)

**Comment by Azmoria** [comment]
I can't replicate this on my end. It's definitely the darkvision/light not rendering properly.

This is what I see when I try it - doesn't seem to trigger no matter how many tokens I drop.
 
![image](https://github.com/cyruzzo/AboveVTT/assets/65363489/da56661a-3fac-449c-887c-cc2d18f922e8)


Just to check to check a few things that might be causing odd behaviour in one browser and not the other:

• Double check hardware acceleration is enabled in chrome
• Possibly another extension interfering - one that adjusts styles/colors on webpages would be most likely but not necessarily one that does
• Make sure chrome is up to date

It doesn't sound hardware related since it's working in firefox for you. 

If none of those things I'm a little stumped. An export of the scene might help to make sure its nothing related to settings or something I'm not testing on my end.

**Comment by trzpiot** [comment]
It was probably due to my system. I use NixOS, the problem no longer exists (with the current NixOS unstable).
