### ISSUE TITLE
Token notes not being synchronised across Chrome instances sharing a profile

### ISSUE THREAD

**Issue by martintoreilly** [cyruzzo/AboveVTT#2443]
Most of the things I do in a campaign in AboveVTT on one of my computers are synchronised to my other computer when using the same Chrome profile with Chrome sync activated. However, token notes seem to be an exception to this. I can only see them on the computer I added them on. I can see addition of tokens and token movements on one computer pretty much instantly on the other, but token notes don't seem to sync.

Is this expected behaviour? If so, is it the desired behaviour or a consequence of how DDB / AboveVTT / Chrome interact? 

I'm not sure if this is linked to #1181 (some assets not being picket up by Chrome).

[Edit: Other token properties such as turning off the border also sync across computers just fine]

**Comment by Azmoria** [comment]
Sorry I didn't back to you sooner token notes and the notes in the journal tab are in local browser storage. 

Where as everything else on a scene is saved on our server. It's suggested to take an export and import on other machines when needing to. 

You can see under the settings tab the things that are local under 'local data exports'. These are also included in the full export though so that's usually easier.

**Comment by martintoreilly** [comment]
Thanks. Sorry for not realising this. I had thought everything was in local storage and that this was  being synchronised by the Chrome synch functionality that synchs bookmarks and history etc.

This makes sense and exporting from one browser and importing on my other machine worked great. Thanks!
