### ISSUE TITLE
Player sheet iframes don’t hide the top bar

### ISSUE THREAD

**Issue by vlaminck** [cyruzzo/AboveVTT#252]
When you click the button to make the sheet thin, DDB injects the header again. This allows you to navigate away from the player sheet inside the iframe

Reported by Azmoria in discord https://discord.com/channels/815028457851191326/815028804103307354/952268152648126496

**Comment by cowoder** [comment]
I'm not familiar with Chrome plugin development, so can't currently offer this as a tested pull request. For now sharing my findings this way.

Here headers get removed: https://github.com/cyruzzo/AboveVTT/blob/ba9bdef7989274818bfdb123527a1bf3ee3716a9/Main.js#L1366-L1370

Smaller screens use `.mega-menu__fallback` which could probably be removed in the same way. Or possibly the entire `.header-wrapper` can be removed instead of current solution.

Might look into how to build the plugin so I can test this when I have some time.
