### ISSUE TITLE
perf issues in the scenes menu

### ISSUE THREAD

**Issue by hypergig** [cyruzzo/AboveVTT#384]
My last game hard crashed the tab 3 times while in the scenes menu. Wasn't able to troubleshoot it in game but it seems to happen when you first open the scenes menu, but only sometimes. There have also been reports of issues that may also have been related to the scenes menu on [discord](https://discord.com/channels/815028457851191326/815028457851191329/960278786488819743).

**Comment by Azmoria** [comment]
I've found the best way to trigger this issue is having a lot of scenes and then moving one around. 

It is slowing down the for loop by applying sortable to the container on every pass. The PR moves the sortable outside the for loop and doesn't call refresh scenes on scene select (this stops it from pushing the scroll to the top).
