### ISSUE TITLE
Allow measuring with the ruler visible while dragging tokens

### ISSUE THREAD

**Issue by vlaminck** [cyruzzo/AboveVTT#453]
This used to work at some point. I believe it was by holding option/alt or something like that. This would be nice to have again.

**Comment by Azmoria** [comment]
Prehaps we can have it as a secondary ruler option. I only suggest this due to the feedback about features that are only available via hotkey. We could still have the hotkey of course.

An aside: If #457 is merged in the tokens will be contained to `#tokens` z-index. If we move `#tokens` z-index above the `fog_overlay` a basic ruler will work on tokens automatically. To get waypoints working we'd have to stop the context menu from popping up. Maybe use the dragging class that gets applied already if that class exists don't open the context menu or something along those lines.
