### ISSUE TITLE
Issue with Super Mega Wizard & Manual Grid Data

### ISSUE THREAD

**Issue by Ron-A-R** [cyruzzo/AboveVTT#717]
I'm trying to load the map for the Well of Dragons and it doesn't load correctly. I've tried over and over again and I cannot get it work. If you have any ideas. Actually most of the maps from Hoard of the Dragon Queen and Rise of Tiamat didn't load at the correct scale.

**Comment by Azmoria** [comment]
I'm guessing when dndbeyond updated those books they updated the maps. Since all of the map configurations are done manually it's using the old settings.

Further issue with this is using the super mega wizard on maps that have a scale that's not 1 causes the grid to be the wrong size. Since Well of Dragons and other large maps have a scale > 1 all attempts to fix the grid fail. 

Work around on live - set the grid scale to 1 under manual grid settings before using the wizard to set the grid.

#719 will fix the super mega wizard issue.

**Comment by Azmoria** [comment]
I'm going to create a 'configure ddb maps' issue for this as the supermega wizard issue has been resolved.
